version: 2.1
orbs:
  docker: circleci/docker@0.5.13
executors:
  python:
    docker:
      - image: circleci/python:3.6.8
jobs:
  test-and-build:
    executor: python
    steps:
      - checkout
      - run: pip install -r requirements.txt --user circleci
      - run: python tests.py
workflows:
  test-and-build:
    jobs:
      - test
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires: 
            - test-and-build
